name: Test

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - uses: actions/upload-artifact@v3

  unit-tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/download-artifact@v3
      - run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/download-artifact@v3
      - run: yarn build

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
      - run: yarn test:e2e
