name: Test

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: public
          retention-days: 1

  unit-tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: workspace
          path: public
      - run: yarn test
      - uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: 'reports/*.xml'

  build:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: workspace
          path: public
      - run: yarn build

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: workspace
          path: public
      - run: yarn test:e2e

